# Welcome to Jekyll!

# Website settings
title: Kang-Hua Wu
description: Kang-Hua's website
keywords: Kang-Hua,Wu,Jekyll,github
baseurl: "" # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://kanghuawu.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Kang-Hua  # Be used at blog posts' author.
  first_name: Kang-Hua  # Be used at index page about me section.
  last_name: Wu  # Be used at index page about me section.
  avatar: /static/assets/img/landing/stephen_github_avatar.jpeg  # upload your avatar at directory and edit it.
  github_username: kanghuawu  # Leave blank if you don't have now
  linkedin_id: kanghuawu # Leave blank if you don't have now
  # facebook_username: jiakunnj  # Leave blank if you don't have now
  # twitter_username: jiakun614  # Leave blank if you don't have now
  email: kang-hua.wu@sjsu.edu  # Leave blank if you don't have now
  cv: https://kanghuawu.github.io/CV/  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-docker
    - name: icon-aws
  skill_icon2:
    - name: icon-java
    - name: icon-python
  desc: Hi, I am Kang-Hua. I worked at TSMC where chips are manufactured for designers such as Apple and Qualcomm. More often than not, the smartphone you are using has chips made by TSMC. Started as semiconductor engineer, I gained experiences in research advanced technology (7/16nm) as well as mass production (28nm). However, it was an internal software tool development turned me into a coding enthusiast. I left the $25 billion revenue company and started my programming journey. Now I am a student at San Jose State University focusing on backend development.  # Describe yourself.

# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-112753021-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

